/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZonasRouteImport } from './routes/zonas'
import { Route as PqrsRouteImport } from './routes/pqrs'
import { Route as MantenimientoRouteImport } from './routes/mantenimiento'
import { Route as FinanzasRouteImport } from './routes/finanzas'
import { Route as DirectorioRouteImport } from './routes/directorio'
import { Route as CopropiedadRouteImport } from './routes/copropiedad'
import { Route as ComunicacionesRouteImport } from './routes/comunicaciones'
import { Route as AsambleasRouteImport } from './routes/asambleas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgReportesRouteImport } from './routes/org/reportes'
import { Route as OrgPanelRouteImport } from './routes/org/panel'
import { Route as OrgEquipoRouteImport } from './routes/org/equipo'
import { Route as OrgCustodiaRouteImport } from './routes/org/custodia'
import { Route as OrgCalendarioRouteImport } from './routes/org/calendario'
import { Route as AdminIaRouteImport } from './routes/admin/ia'
import { Route as AdminConsoleRouteImport } from './routes/admin/console'
import { Route as AdminBillingRouteImport } from './routes/admin/billing'
import { Route as AdminAuditoriaRouteImport } from './routes/admin/auditoria'

const ZonasRoute = ZonasRouteImport.update({
  id: '/zonas',
  path: '/zonas',
  getParentRoute: () => rootRouteImport,
} as any)
const PqrsRoute = PqrsRouteImport.update({
  id: '/pqrs',
  path: '/pqrs',
  getParentRoute: () => rootRouteImport,
} as any)
const MantenimientoRoute = MantenimientoRouteImport.update({
  id: '/mantenimiento',
  path: '/mantenimiento',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanzasRoute = FinanzasRouteImport.update({
  id: '/finanzas',
  path: '/finanzas',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorioRoute = DirectorioRouteImport.update({
  id: '/directorio',
  path: '/directorio',
  getParentRoute: () => rootRouteImport,
} as any)
const CopropiedadRoute = CopropiedadRouteImport.update({
  id: '/copropiedad',
  path: '/copropiedad',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunicacionesRoute = ComunicacionesRouteImport.update({
  id: '/comunicaciones',
  path: '/comunicaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const AsambleasRoute = AsambleasRouteImport.update({
  id: '/asambleas',
  path: '/asambleas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgReportesRoute = OrgReportesRouteImport.update({
  id: '/org/reportes',
  path: '/org/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgPanelRoute = OrgPanelRouteImport.update({
  id: '/org/panel',
  path: '/org/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgEquipoRoute = OrgEquipoRouteImport.update({
  id: '/org/equipo',
  path: '/org/equipo',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgCustodiaRoute = OrgCustodiaRouteImport.update({
  id: '/org/custodia',
  path: '/org/custodia',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgCalendarioRoute = OrgCalendarioRouteImport.update({
  id: '/org/calendario',
  path: '/org/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIaRoute = AdminIaRouteImport.update({
  id: '/admin/ia',
  path: '/admin/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConsoleRoute = AdminConsoleRouteImport.update({
  id: '/admin/console',
  path: '/admin/console',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/admin/billing',
  path: '/admin/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/admin/auditoria',
  path: '/admin/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asambleas': typeof AsambleasRoute
  '/comunicaciones': typeof ComunicacionesRoute
  '/copropiedad': typeof CopropiedadRoute
  '/directorio': typeof DirectorioRoute
  '/finanzas': typeof FinanzasRoute
  '/mantenimiento': typeof MantenimientoRoute
  '/pqrs': typeof PqrsRoute
  '/zonas': typeof ZonasRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/console': typeof AdminConsoleRoute
  '/admin/ia': typeof AdminIaRoute
  '/org/calendario': typeof OrgCalendarioRoute
  '/org/custodia': typeof OrgCustodiaRoute
  '/org/equipo': typeof OrgEquipoRoute
  '/org/panel': typeof OrgPanelRoute
  '/org/reportes': typeof OrgReportesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asambleas': typeof AsambleasRoute
  '/comunicaciones': typeof ComunicacionesRoute
  '/copropiedad': typeof CopropiedadRoute
  '/directorio': typeof DirectorioRoute
  '/finanzas': typeof FinanzasRoute
  '/mantenimiento': typeof MantenimientoRoute
  '/pqrs': typeof PqrsRoute
  '/zonas': typeof ZonasRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/console': typeof AdminConsoleRoute
  '/admin/ia': typeof AdminIaRoute
  '/org/calendario': typeof OrgCalendarioRoute
  '/org/custodia': typeof OrgCustodiaRoute
  '/org/equipo': typeof OrgEquipoRoute
  '/org/panel': typeof OrgPanelRoute
  '/org/reportes': typeof OrgReportesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asambleas': typeof AsambleasRoute
  '/comunicaciones': typeof ComunicacionesRoute
  '/copropiedad': typeof CopropiedadRoute
  '/directorio': typeof DirectorioRoute
  '/finanzas': typeof FinanzasRoute
  '/mantenimiento': typeof MantenimientoRoute
  '/pqrs': typeof PqrsRoute
  '/zonas': typeof ZonasRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/console': typeof AdminConsoleRoute
  '/admin/ia': typeof AdminIaRoute
  '/org/calendario': typeof OrgCalendarioRoute
  '/org/custodia': typeof OrgCustodiaRoute
  '/org/equipo': typeof OrgEquipoRoute
  '/org/panel': typeof OrgPanelRoute
  '/org/reportes': typeof OrgReportesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asambleas'
    | '/comunicaciones'
    | '/copropiedad'
    | '/directorio'
    | '/finanzas'
    | '/mantenimiento'
    | '/pqrs'
    | '/zonas'
    | '/admin/auditoria'
    | '/admin/billing'
    | '/admin/console'
    | '/admin/ia'
    | '/org/calendario'
    | '/org/custodia'
    | '/org/equipo'
    | '/org/panel'
    | '/org/reportes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asambleas'
    | '/comunicaciones'
    | '/copropiedad'
    | '/directorio'
    | '/finanzas'
    | '/mantenimiento'
    | '/pqrs'
    | '/zonas'
    | '/admin/auditoria'
    | '/admin/billing'
    | '/admin/console'
    | '/admin/ia'
    | '/org/calendario'
    | '/org/custodia'
    | '/org/equipo'
    | '/org/panel'
    | '/org/reportes'
  id:
    | '__root__'
    | '/'
    | '/asambleas'
    | '/comunicaciones'
    | '/copropiedad'
    | '/directorio'
    | '/finanzas'
    | '/mantenimiento'
    | '/pqrs'
    | '/zonas'
    | '/admin/auditoria'
    | '/admin/billing'
    | '/admin/console'
    | '/admin/ia'
    | '/org/calendario'
    | '/org/custodia'
    | '/org/equipo'
    | '/org/panel'
    | '/org/reportes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsambleasRoute: typeof AsambleasRoute
  ComunicacionesRoute: typeof ComunicacionesRoute
  CopropiedadRoute: typeof CopropiedadRoute
  DirectorioRoute: typeof DirectorioRoute
  FinanzasRoute: typeof FinanzasRoute
  MantenimientoRoute: typeof MantenimientoRoute
  PqrsRoute: typeof PqrsRoute
  ZonasRoute: typeof ZonasRoute
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminConsoleRoute: typeof AdminConsoleRoute
  AdminIaRoute: typeof AdminIaRoute
  OrgCalendarioRoute: typeof OrgCalendarioRoute
  OrgCustodiaRoute: typeof OrgCustodiaRoute
  OrgEquipoRoute: typeof OrgEquipoRoute
  OrgPanelRoute: typeof OrgPanelRoute
  OrgReportesRoute: typeof OrgReportesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zonas': {
      id: '/zonas'
      path: '/zonas'
      fullPath: '/zonas'
      preLoaderRoute: typeof ZonasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pqrs': {
      id: '/pqrs'
      path: '/pqrs'
      fullPath: '/pqrs'
      preLoaderRoute: typeof PqrsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mantenimiento': {
      id: '/mantenimiento'
      path: '/mantenimiento'
      fullPath: '/mantenimiento'
      preLoaderRoute: typeof MantenimientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finanzas': {
      id: '/finanzas'
      path: '/finanzas'
      fullPath: '/finanzas'
      preLoaderRoute: typeof FinanzasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directorio': {
      id: '/directorio'
      path: '/directorio'
      fullPath: '/directorio'
      preLoaderRoute: typeof DirectorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copropiedad': {
      id: '/copropiedad'
      path: '/copropiedad'
      fullPath: '/copropiedad'
      preLoaderRoute: typeof CopropiedadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunicaciones': {
      id: '/comunicaciones'
      path: '/comunicaciones'
      fullPath: '/comunicaciones'
      preLoaderRoute: typeof ComunicacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asambleas': {
      id: '/asambleas'
      path: '/asambleas'
      fullPath: '/asambleas'
      preLoaderRoute: typeof AsambleasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/reportes': {
      id: '/org/reportes'
      path: '/org/reportes'
      fullPath: '/org/reportes'
      preLoaderRoute: typeof OrgReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/panel': {
      id: '/org/panel'
      path: '/org/panel'
      fullPath: '/org/panel'
      preLoaderRoute: typeof OrgPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/equipo': {
      id: '/org/equipo'
      path: '/org/equipo'
      fullPath: '/org/equipo'
      preLoaderRoute: typeof OrgEquipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/custodia': {
      id: '/org/custodia'
      path: '/org/custodia'
      fullPath: '/org/custodia'
      preLoaderRoute: typeof OrgCustodiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/calendario': {
      id: '/org/calendario'
      path: '/org/calendario'
      fullPath: '/org/calendario'
      preLoaderRoute: typeof OrgCalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ia': {
      id: '/admin/ia'
      path: '/admin/ia'
      fullPath: '/admin/ia'
      preLoaderRoute: typeof AdminIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/console': {
      id: '/admin/console'
      path: '/admin/console'
      fullPath: '/admin/console'
      preLoaderRoute: typeof AdminConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/admin/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/admin/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsambleasRoute: AsambleasRoute,
  ComunicacionesRoute: ComunicacionesRoute,
  CopropiedadRoute: CopropiedadRoute,
  DirectorioRoute: DirectorioRoute,
  FinanzasRoute: FinanzasRoute,
  MantenimientoRoute: MantenimientoRoute,
  PqrsRoute: PqrsRoute,
  ZonasRoute: ZonasRoute,
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminConsoleRoute: AdminConsoleRoute,
  AdminIaRoute: AdminIaRoute,
  OrgCalendarioRoute: OrgCalendarioRoute,
  OrgCustodiaRoute: OrgCustodiaRoute,
  OrgEquipoRoute: OrgEquipoRoute,
  OrgPanelRoute: OrgPanelRoute,
  OrgReportesRoute: OrgReportesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
